version: '3.9'

services:
    # Databases
    # Account Database
    mysql_account:
        image: mysql/mysql-server:latest
        ports:
            - "3310:3306"
        restart: always
        volumes:
            - db_volume_Accounts:/var/lib/mysql
            - ../db/Accounts.sql:/docker-entrypoint-initdb.d/Accounts.sql:ro
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_HOST: localhost
            MYSQL_DATABASE: "Accounts"
            MYSQL_USER: "root"
        container_name: db_Accounts
    #Public Library Database
    mongo_public_library:
        image: mongo:4.4.4
        ports: 
            - "3311:27019"
        restart: always
        volumes:
            - db_volume_public_library:/var/lib/mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: spotymeAdmin
            MONGO_INITDB_ROOT_PASSWORD: proyectoredes
        container_name: db_public_library
    #Private Library Database
    mongo_private_library:
        image: mongo:4.4.4
        ports: 
            - "3312:27019"
        restart: always
        volumes:
            - db_volume_private_library:/var/lib/mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: spotymeAdmin
            MONGO_INITDB_ROOT_PASSWORD: proyectoredes
        container_name: db_private_library
    # Microservicios
    # Servicio de cuentas
    ms_account:
        image: ms_account_spotyme
        depends_on: 
            - "mysql_account"
        ports:
            - "8080:80"
        build: 
            context: ../MSAccount/
            dockerfile: Dockerfile
        environment: 
            DB_CONNECTION_STRING: "server=mysql_account;user=spotymeAdmin;password=proyectoredes;database=Accounts"
    # Servicio de biblioteca publica
    ms_public_library:
        image: ms_public_library_spotyme
        depends_on: 
            - "mongo_public_library"
        ports:
            - "8081:80"
        build: 
            context: ../MSPublicLibrary/
            dockerfile: Dockerfile
        environment: 
            DB_CONNECTION_STRING: "mongodb://spotymeAdmin:proyectoredes@db_public_library:3311"
volumes:
    db_volume_Accounts:
    db_volume_public_library:
    db_volume_private_library: