version: '3.9'

services:
    # Databases
    # Account Database
    mysql_account:
        image: mysql/mysql-server:latest
        ports:
            - "3310:3306"
        restart: always
        volumes:
            - db_volume_Accounts:/var/lib/mysql
            - ../db/Accounts.sql:/docker-entrypoint-initdb.d/Accounts.sql:ro
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_HOST: localhost
            MYSQL_DATABASE: "Accounts"
            MYSQL_USER: "root"
        container_name: db_Accounts
    #Public Libraries Database
    mysql_public_library:
        image: mysql/mysql-server:latest
        ports:
            - "3309:3306"
        restart: always
        volumes:
            - db_volume_Libraries:/var/lib/mysql
            - ../db/Libraries.sql:/docker-entrypoint-initdb.d/Libraries.sql:ro
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_HOST: localhost
            MYSQL_DATABASE: "Libraries"
            MYSQL_USER: "root"
        container_name: db_Public_Library
    #Private Libraries Database
    mysql_private_library:
        image: mysql/mysql-server:latest
        ports:
            - "3308:3306"
        restart: always
        volumes:
            - db_volume_Libraries:/var/lib/mysql
            - ../db/Libraries.sql:/docker-entrypoint-initdb.d/Libraries.sql:ro
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_HOST: localhost
            MYSQL_DATABASE: "Libraries"
            MYSQL_USER: "root"
        container_name: db_Private_Library
    #Music metadata database
    mongo_music:
        image: mongo:4.4.4
        ports: 
            - "3311:27019"
        restart: always
        volumes:
            - db_volume_Music:/var/lib/mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: spotymeAdmin
            MONGO_INITDB_ROOT_PASSWORD: proyectoredes
        container_name: db_Music
    # Microservicios
    ms_account:
        image: ms_account_spotyme
        depends_on: 
            - "mysql_account"
        ports:
            - "8080:80"
        build: 
            context: ../MSAccount/
            dockerfile: Dockerfile
        environment: 
            DB_CONNECTION_STRING: "server=mysql_account;user=spotymeAdmin;password=proyectoredes;database=Account"
    ms_public_library:
        image: ms_public_library_spotyme
        depends_on: 
            - "mysql_public_library"
        ports:
            - "8081:80"
        build: 
            context: ../MSPublicLibrary/
            dockerfile: Dockerfile
        environment: 
            DB_CONNECTION_STRING: "server=mysql_public_library;user=spotymeAdmin;password=proyectoredes;database=Libraries"
volumes:
    db_volume_Accounts:
    db_volume_Libraries:
    db_volume_Music: